apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
images:
- name: goserver
  newName: lucianotulio/gitopsdd
  newTag: 7656b0288557569f2df3511979225f53a59871dd
