name: CD Gitops 

on: 
  push: 
    branches: [main]

  jobs: 
    build:
      name: Build
      runs-on: ubuntu-latest 

      steps: 
      -  name: Checkout code 
         uses: actions/checkout@v2

      -  name: Build nad push image to Dockerhub
         uses: dicker/build-push-action@v1.1.0 
         with: 
          username: ${{ secrets.DOCKER_USERNAME }}
          PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ secrets.DOCKER_USERNAME }}/gitopsdd
          tags: ${{ gitgub.sha }}  latest 

      
        